### ISSUE TITLE
Some dependencies in _oasis have incorrect capitalization for Linux

### ISSUE THREAD

**Issue by andreyiv** [chenglou/ocaml-better-errors#12]
Pcre and Batteries tend to not be found by ocamlfind on Linux unless written in all lower case in _oasis file. ANSITerminal is correct as is. Does ocamlfind running on MacOS care for capitalization either way?

Wanted to check to make sure before creating a Pull request, just in case lower case P and B in Pcre and Batteries is not compatible everywhere. Unfortunately I currently don't have access to MacOS to give it a try.

**Comment by chenglou** [comment]
I believe this is fixed in #14.

And no, OSX doesn't care. Sorry for the trouble.
