### ISSUE TITLE
Investigate whether every error & warning has a file name output

### ISSUE THREAD

**Issue by chenglou** [chenglou/ocaml-better-errors#4]
Is there any weird (e.g. buildFailure, fileNotFound) error/warning that does **not** output a file name? If everything outputs a file name **and** line info we could use that assumption to reorganize some logic.

@bsansouci

**Comment by chenglou** [comment]
Welp, the first test in the repo (unparsed for now) doesn't have a file character info (bad file name test)

**Comment by chenglou** [comment]
Yeah kinda.

**Comment by bsansouci** [comment]
"Kinda" haha
